# Generated by Django 3.2.11 on 2022-01-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20220105_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='rno',
            field=models.ForeignKey(db_column='rNo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderform',
            name='cno',
            field=models.ForeignKey(db_column='cNo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderform',
            name='dno',
            field=models.ForeignKey(db_column='dNo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.deliveryman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderform',
            name='fno',
            field=models.ForeignKey(db_column='fNo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
