# Generated by Django 3.2.11 on 2022-01-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20220105_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cno',
            field=models.AutoField(db_column='cNo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='dno',
            field=models.AutoField(db_column='dNo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='fno',
            field=models.AutoField(db_column='fNo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='ono',
            field=models.AutoField(db_column='oNo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rno',
            field=models.AutoField(db_column='rNo', primary_key=True, serialize=False),
        ),
    ]
